### ISSUE TITLE
Passing URL to Spider

### ISSUE THREAD

**Issue by ghost** [invertpyramid/s-whoscored#1]
How are you passing the url to the browser?

**Comment by grammy-jiang** [comment]
Hi, sorry I didn't finish this spider.

After many failures, I gave up Scrapy + Pyppeteer. I tried many ways in Scrapy, I can pass the url to Chrome but Captcha pops up, and I am really tired to crack Captcha again. So I turned to Puppeteer to munipulate Chrome directly, and finally it works.

So if you really want a solution, I highly recommand to try Puppeteer for this.
